apps/element/urls.py
from django.urls import path
from .views.cast import (AddCast, UpdateCast, CastProfile,
                         AddActorToMovie, AddDirectorToMovie,
                         remove_actor_from_movie, remove_director_from_movie,
                            DeleteCast)

from .views.genre import  AddGenre, AddGenreToMovie, remove_genre_from_movie

app_name = "element"

urlpatterns = [
    path("add-genre/",AddGenre.as_view(),name="add-genre"),
    path("add-cast/",AddCast.as_view(),name="add-cast"),
    path('add-actor/<str:token>/', AddActorToMovie.as_view(), name="add-actor-to-movie"),
    path('delete-cast/<str:token>/', DeleteCast.as_view(), name="delete-cast"),

    path('add-director/<str:token>/', AddDirectorToMovie.as_view(), name="add-director-to-movie"),
    path('remove-actor/<str:film>/<str:actor>/', remove_actor_from_movie, name="remove-actor-from-movie"),
    path('remove-director/<str:film>/<str:director>/', remove_director_from_movie, name="remove-director-from-movie"),
    path('remove-genre/<str:film>/<str:genre>/', remove_genre_from_movie, name="remove-genre-from-movie"),


    path('add-genre/<str:token>/', AddGenreToMovie.as_view(), name="add-genre-to-movie"),


    path("update-cast/<str:token>/",UpdateCast.as_view(),name="update-cast"),
    path("cast-profile/<str:token>/",CastProfile.as_view(),name="profile")
]

apps/movie/urls.py
from django.urls import path
from .views.film import (
    AddMovie, UpdateMovie,
       FilmDetail, DeleteMovie)

from .views.core import (
        HomePage, SearchFilm, FilterGenre
)

from .views.season import AddSeason, SeasonDetail, DeleteSeason

app_name = "movie"

urlpatterns = [
    path("", HomePage, name="home"),

    path("movie-detail/<str:token>/", FilmDetail.as_view(), name="film-detail"),
    path("season-detail/<str:token>/", SeasonDetail.as_view(), name="season-detail"),
    path("add-movie/", AddMovie.as_view(), name="add-movie"),
    path("update-movie/<str:token>/", UpdateMovie.as_view(), name="update-movie"),
    path("delete-movie/<str:token>/", DeleteMovie.as_view(), name="delete-movie"),
    path("add-season/<str:token>/", AddSeason.as_view(), name="add-season"),
    path("delete-season/<str:token>/", DeleteSeason.as_view(), name="delete-season"),

    path("search/<str:name>/", SearchFilm.as_view(), name="search-film"),
    path("filter-genre/<str:genre>/", FilterGenre.as_view(), name="filter-genre"),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("auth/",include("allauth.urls")),
    path("element/",include("apps.element.urls")),
    path("",include("apps.movie.urls")),
    path("api/v1/",include("apps.api.v1.urls")),
    path("api/v2/",include("apps.api.v2.urls")),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'apps.movie.views.core.handler404'
handler500 = 'apps.movie.views.core.handler500'

apps/movie/models.py
from django.db import models
from django.contrib.contenttypes.fields import GenericRelation
from star_ratings.models import Rating
from element.models import Cast,Genre
# Create your models here.

class Film(models.Model):
    picture = models.ImageField(upload_to="Movie-images")
    name = models.CharField(max_length=20)
    intro = models.TextField()
    imdb = models.PositiveIntegerField(default=0)
    actors= models.ManyToManyField(Cast, related_name='movie_actor',blank=True)
    director= models.ManyToManyField(Cast, related_name='movie_director',blank=True)
    genre= models.ManyToManyField(Genre, related_name='movie_genre', blank=True)
    ratings = GenericRelation(Rating, related_query_name='rate')
    release_date = models.DateField()
    token = models.CharField(max_length=15,unique=True,null=True,blank=True)
    views = models.ManyToManyField("View", blank=True)
    def __str__(self) :
        return self.name
    
        

class Season(models.Model):
    '''Season model for series'''

    number = models.PositiveIntegerField(default=1)
    film = models.ForeignKey("Film", blank=True, on_delete=models.CASCADE, related_name="seasons")
    story = models.TextField(null=True,blank=True)
    token = models.CharField(max_length=10, blank=True)

    def __str__(self) -> str:
        return f'{str(self.number)} | {self.film}'


class View(models.Model):
    user_ip = models.GenericIPAddressField()
    def __str__(self) -> str:
        return self.user_ip

apps/movie/forms.py
from django import forms 
from django.forms import ModelForm
from movie.models import Film, Season

class MovieForm(ModelForm):
    '''A form for creating Movies'''

    class Meta:
        model  = Film
        fields = ["name", "picture", "intro", "imdb", "release_date"]


class SeasonForm(ModelForm):
    '''A form for adding season to series'''

    class Meta:
        model = Season
        fields = ["number", "film", "story"]

apps/movie/views/core.py
from django.shortcuts import render
from django.views.generic import  ListView
from django.db.models import Count

from element.models import Cast, Genre
from movie.models import Film


# Create your views here.

def HomePage(request):
    '''
        Home page includes List of recent movies, genres and top rated item
    '''
    films = Film.objects.all().order_by('-ratings__average')[:50]
    genre = Genre.objects.annotate(films=Count('movie_genre')).order_by('-films')

    return render(request, "base/home.html", {"films": films, "genres": genre})


def search_film(request):
    # Search film func
    if request.method == "POST":
        searched = request.POST['search_field']
        film = Film.objects.filter(name__contains=searched)
        return render(request,
                      'base/search-result.html',
                      {'searched': searched,
                       'film': film})
    else:
        return render(request,
                      'base/search-result.html',
                      {})


class SearchFilm(ListView):
    '''
        Result of items that user searched for
    '''
    template_name = 'base/search-result.html'

    def get_queryset(self):
        return Film.objects.filter(name__icontains=self.kwargs['name'])


class FilterGenre(ListView):
    '''
        Filter movies by genre
    '''
    template_name = 'movie/movie/filter-film.html'

    def get_queryset(self):
        print(self.kwargs['genre'])
        return Film.objects.filter(genre__title__in=[self.kwargs['genre']])


def handler404(request, exception=None):
    '''
        404 page
    '''
    return render(request, "base/errors/404.html", {})


def handler500(request, exception=None):
    '''
        500 error page
    '''
    return render(request, "base/errors/500.html", {})

apps/movie/views/film.py
from django.shortcuts import redirect, get_object_or_404
from django.views.generic import FormView, DetailView, UpdateView, DeleteView
from django.db import transaction
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
import uuid

from element.models import Cast, Genre
from movie.models import Film
from movie.forms import MovieForm


class AddMovie(LoginRequiredMixin, FormView):
    '''Create a new film'''

    template_name = "movie/movie/add-movie.html"
    form_class = MovieForm

    @transaction.atomic
    def form_valid(self, form):
        form = self.form_class(self.request.POST, self.request.FILES)

        form = form.save(commit=False)

        # check if film does not exist
        if Film.objects.filter(name= form.name,
                               release_date=form.release_date).exists():
            return redirect("movie:home")

        # assign a new token
        form.token = uuid.uuid4().hex.upper()[0:15]

        form.save()
        return redirect("movie:film-detail", token=form.token)

    def form_invalid(self, form):
        return redirect("movie:home")


class FilmDetail(DetailView):
    '''
        Film detail shows extra info about the object such as seasons, actors ...
    '''
    template_name = "movie/movie/movie-detail.html"
    def get_object(self, *args, **kwargs):
        object = get_object_or_404(Film,token=self.kwargs['token'])
        ip_address = self.request.user.ip_address
        if ip_address not in object.views.all():
            object.views.add(ip_address)
        return object


class UpdateMovie(LoginRequiredMixin,UpdateView):
    '''Update A Movie'''
    template_name = "movie/movie/update-movie.html"
    fields = fields = "picture", "name", "intro", "imdb", "release_date"

    def get_object(self):
        return get_object_or_404(Film, token=self.kwargs['token'])

    def get_success_url(self):
        return reverse_lazy("movie:film-detail", kwargs={ "token": self.get_object().token })

    def form_invalid(self,form):
        return redirect("movie:film-detail", self.get_object().token)


class DeleteMovie(LoginRequiredMixin, DeleteView):
    '''Delete a Movie'''

    template_name = "movie/movie/delete-movie.html"
    success_url = "/"

    def get_object(self):
        return get_object_or_404(Film, token=self.kwargs["token"])

apps/movie/views/season.py
from django.shortcuts import redirect, get_object_or_404
from django.views.generic import FormView, DetailView, UpdateView, DeleteView
from django.db import transaction
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

import uuid

from movie.models import Film, Season
from movie.forms import SeasonForm



class AddSeason(LoginRequiredMixin, FormView):
    '''
        Add seasons for series they've created
    '''

    template_name = "movie/season/add-season.html"
    form_class = SeasonForm

    # @transaction.atomic
    def form_valid(self, form):
        data = form.save(commit=False)

        # get the related series
        series = get_object_or_404(Film, token= self.kwargs['token'])

        # check if this season was not created
        if Season.objects.filter(number=data.number).exists():
            return redirect("movie:film-detail", token=series.token)

        data.token = uuid.uuid4().hex.upper()[0:10]
        data.film = series
        data.save()

        return redirect("movie:film-detail", token=series.token)


    def form_invalid(self, form):
        return redirect("movie:home")


class SeasonDetail(DetailView):
    '''
        Season detail shows extra info about a series season
    '''
    template_name = "movie/season/season-detail.html"
    def get_object(self, *args, **kwargs):
        object = get_object_or_404(Season,token=self.kwargs['token'])
        return object


class DeleteSeason(LoginRequiredMixin, DeleteView):
    '''Delete a Season'''

    template_name = "movie/movie/delete-season.html"

    def get_object(self):
        return get_object_or_404(Season, token=self.kwargs["token"])

    def get_success_url(self):
        return reverse_lazy("movie:film-detail", kwargs={"token": self.get_object().film.token})

apps/movie/templates/movie/movie/add-movie.html
{%extends 'movie/base-movie.html'%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{%block title%}Add Movie{%endblock%}</title>
   {%block page_title%}Add Movie{%endblock%}
</head>

<body>
    <form method="post" enctype="multipart/form-data">{%csrf_token%}

        {%block main%}
            <h3>General info</h3>
            <div class="input__item">
                <input name="name" type="text" placeholder="Title" maxlength="100" style="width: 10cm; height: 1.3cm;">
            </div> <br>

            <div class="input__item">
                <input name="intro" type="text" placeholder="Tell us a short intro..." maxlength="500" style="width: 10cm; height: 1.3cm;">
            </div><br>

            <div class="input__item">
                <input name="imdb" type="number" placeholder="imdb" maxlength="2" style="width: 10cm; height: 1.3cm;">
            </div>

        {%endblock%}

        {% block side %}
            <label style="color: white;" for="picture">Picture</label>

            <div class="input__item">
                <input name="picture" type="file" >
            </div>  <br>
            <div class="input__item">
                <input name="release_date" type="date" placeholder="release date" style="width: 10cm; height: 1.3cm;">
            </div>
            <br><button type="submit" class="site-btn">Submit</button>
        {%endblock%}
    </form>


</body>
</html>

apps/movie/templates/movie/movie/delete-movie.html
{%extends 'movie/base-movie.html'%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{%block title%}Delete Movie{%endblock%}</title>
   {%block page_title%}Delete Movie{%endblock%}
</head>
<body>
<form method="post" enctype="multipart/form-data">{%csrf_token%}
    {%block main%}
          <h3 style="color:white;">Are  you sure you wanna delete {{ object.name }}??</h3>
    {%endblock%}

    {% block side %}
      <a href="{% url 'movie:film-detail' object.token %}" class="site-btn">No, return to detail page</a> <br><br>
      <button type="submit" class="site-btn">Delete</button>
    {%endblock%}

    </form>
</body>
</html>

apps/movie/templates/movie/movie/delete-season.html
{%extends 'movie/base-movie.html'%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{%block title%}Delete Season{%endblock%}</title>
   {%block page_title%}Delete Season{%endblock%}
</head>
<body>
<form method="post" enctype="multipart/form-data">{%csrf_token%}
    {%block main%}
          <h3 style="color:white;">Are  you sure you wanna delete {{ object.number }} | {{ object.film.name }}??</h3>
    {%endblock%}

    {% block side %}
      <a href="{% url 'movie:season-detail' object.token %}" class="site-btn">No, return to detail page</a> <br><br>
      <button type="submit" class="site-btn">Delete</button>
    {%endblock%}

    </form>
</body>
</html>

apps/movie/templates/movie/movie/filter-film.html
{%extends 'base/base.html'%}
{% load ratings %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   
    <title>{%block title%}Filter page{%endblock%}</title>
</head>
<body>
    {%block body%}
    <section class="anime-details spad">
        <div class="container">
            <div class="anime__details__content">
                <div class="row">
                        <div class="col-lg-8 col-md-8">
                            <div class="anime__details__review">
                                <div class="section-title">
                                    <h5>Result:</h5>
                                </div>
                                {%if not object_list%}
                                <div class="anime__review__item">
                                    <div class="anime__review__item__text">
                                        <h6>No result found</h6>
                                    </div>
                                </div>
                                {%else%}
                                {%for film in object_list%}
                                <h3>{{film.count}}1</h3>
                                    {%if film.count == 0%}
                                        <h3>No result found</h3>
                                    {%else%}
                                        <div class="anime__review__item">
                                            <div class="anime__review__item__pic">
                                                <img src="{{film.picture.url}}" alt="">
                                            </div>
                                            <div class="anime__review__item__text">
                                                <a href="{%url 'movie:film-detail' film.token%}"><h6>{{film.name}}</h6></a>
                                                <a href="{%url 'movie:film-detail' film.token%}"><p>{{film.intro | truncatewords:15}}...</p></a>
                                            </div>
                                        </div>
                                    </div>
                                    {%endif%}
                                {%endfor%}
                                {%endif%}
                                
                        </div>
                    </div>
                </div>
            </div>
        </section>
    {%endblock%}
</body>
</html>

apps/movie/templates/movie/movie/movie-detail.html
{%extends 'base/base.html'%}
{% load ratings %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   
    <title>{%block title%}{{ object.name }}{%endblock%}</title>
</head>
<body>
    {%block body%}
    <section class="anime-details spad">
        <div class="container">
            <div class="anime__details__content">
                <div class="row">
                    <div class="col-lg-3">
                        <div class="anime__details__pic set-bg">
                            <img src="{{object.picture.url}}" alt="pic">
                            <div class="comment"><i class="fa fa-star"></i> {{object.imdb}}/10</div>
                            <div class="view"><i class="fa fa-eye"></i> {{object.views.count}}</div>
                        </div>
                    </div>
                        <div class="col-lg-9">
                            <div class="anime__details__text">
                                <div class="anime__details__title">
                                    <h3>{{object.name}}</h3>
                                    <span>A film by {%for director in object.director.all %}
                                        {{director}} |
                                        {%endfor%} </span>
                                </div>
                                <div class="anime__details__rating">
                                    {% ratings object %}

                                </div>
                                <p>{{object.intro}}</p>
                                <div class="anime__details__widget">
                                    <div class="row">
                                        
                                        <div class="col-lg-6 col-md-6">
                                            <ul>
                                                
                                                <li><span>Type:</span>{%if object.seasons.count == 0%}Film{%else%}TV Series{%endif%}</li>
                                                <li><span>Date Released:</span> {{object.release_date}}</li>
                                                <li><span>imdb:</span>{{object.imdb}}/10</li>
                                                <li><span>Genre:</span>
                                                    {%for genre in object.genre.all %}
                                                        <a href="{% url 'movie:filter-genre' genre %}">{{genre}}</a>
                                                        {% if request.user.is_authenticated %}
                                                            <a href="{% url 'element:remove-genre-from-movie' object.token genre %}"> | Remove</a>
                                                        {% endif %}
                                                    {% empty %}
                                                        <a href="{% url 'element:add-genre-to-movie' object.token %}">Empty, Add New One</a>
                                                    {%endfor%}
                                                </li>
                                                <li><span>
                                                    Directors:
                                                </span> {%for director in object.director.all %}
                                                            <a href="{% url 'element:profile' director.token %}">{{director}}, </a>
                                                            {% if request.user.is_authenticated %}
                                                                <a href="{% url 'element:remove-director-from-movie' object.token director.token %}"> | Remove</a>
                                                            {% endif %}

                                                        {% empty %}
                                                            <a href="{% url 'element:add-director-to-movie' object.token %}">Empty, Add New One</a>

                                                    {%endfor%}</li>
                                            </ul>
                                        </div>
                                </div>
                                {%if request.user.is_authenticated%}
                                    <div class="anime__details__btn">
                                        <a href="{%url 'movie:update-movie' object.token%}" class="follow-btn">Update</a>
                                        <a href="{%url 'movie:delete-movie' object.token%}" class="follow-btn">Delete</a>
                                        <a href="{%url 'movie:add-season' object.token%}" class="follow-btn">Add Season</a>
                                        <a href="{%url 'element:add-actor-to-movie' object.token%}" class="follow-btn">Add Actor</a>
                                        <a href="{%url 'element:add-director-to-movie' object.token%}" class="follow-btn">Add Director</a>
                                    </div>

                                    </div>
                                {%endif%}
                            </div>
                        </div>
                </div>


                <div class="row">
                    <div class="col-lg-8 col-md-8">
                        <div class="anime__details__review">
                            {% if object.seasons.count != 0 %}
                                <div class="section-title">
                                    <h5>Seasons</h5>
                                </div>
                                    {%for season in object.seasons.all %}
                                        <div class="anime__review__item">
                                            <div class="anime__review__item__text">
                                                <a href="{%url 'movie:season-detail' season.token %}"><h6>{{season.number}} | {{object.name}}</h6></a>
                                                {% if request.user.is_authenticated %}
                                                    <a href="{% url 'movie:delete-season' season.token %}"><h6>Remove Season</h6></a>
                                                    {% endif %}
                                                <p>{{season.story | truncatewords:30}}</p>
                                            </div>
                                        </div>
                                    {%endfor%}
                            </div>
                        {% endif %}
                    </div>


                    <div class="col-lg-4 col-md-4">
                        <div class="anime__details__sidebar">
                            <div class="section-title">
                                <h5>Actors</h5>
                            </div>
                            {%for actor in object.actors.all %}
                                <div class="product__sidebar__view__item set-bg">
                                    <h5><a href="{%url 'element:profile' actor.token %}">{{actor.full_name}} </a>
                                    {% if request.user.is_authenticated %}<a href="{% url 'element:remove-actor-from-movie' object.token actor.token %}">
                                            | Remove</a>{% endif %}</h5>
                                </div>
                            {% empty %}
                                    <div class="product__sidebar__view__item set-bg">
                                    <h5><a href="{%url 'element:add-actor-to-movie' object.token %}">Add Actor</a></h5>
                                </div>
                            {%endfor%}
                        </div>
                    </div>
                </div>
            </div>
        </section>
    {%endblock%}
</body>
</html>

apps/movie/templates/movie/movie/update-movie.html
{%extends 'movie/base-movie.html'%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{%block title%}Update Movie{%endblock%}</title>
   {%block page_title%}Update Movie{%endblock%}
</head>
<body>
<form method="post" enctype="multipart/form-data">{%csrf_token%}
    {%block main%}
            <div class="input__item">
                <input name="name" type="text" value="{{form.name.value}}" placeholder="Name" style="width: 10cm; height: 1.3cm;" maxlength="20">
            </div>

            <div class="input__item">
                <input name="intro" type="text" value="{{form.intro.value}}" placeholder="Tell us a short intro..." style="width: 10cm; height: 1.3cm;" maxlength="50">
            </div>

            <div class="input__item">
                <input name="imdb" type="number" value="{{form.imdb.value}}" placeholder="imdb" style="width: 10cm; height: 1.3cm;" maxlength="2">
            </div>
            {%endblock%}

            {% block side %}
                    <label style="color: white;" for="picture">Picture</label>
                    <div class="input__item">
                        <input name="picture" type="file" value="{{form.picture.value}}" >
                    </div>  <br>
                    <div class="input__item">
                        <input name="release_date" type="date" placeholder="release date" value="{{ form.release_date.value }}" style="width: 10cm; height: 1.3cm;" maxlength="20">
                    </div>
                    <div class="input__item">
                        <input name="token"  value="{{form.token.value}}" type="text"  style="width: 10cm; height: 1.3cm;" maxlength="20">
                    </div>
                    <br><br><button type="submit" class="site-btn">Submit</button>
                </div>
            {%endblock%}


    </form>
</body>
</html>