apps/element/urls.py
from django.urls import path
from .views.cast import (AddCast, UpdateCast, CastProfile,
                         AddActorToMovie, AddDirectorToMovie,
                         remove_actor_from_movie, remove_director_from_movie,
                            DeleteCast)

from .views.genre import  AddGenre, AddGenreToMovie, remove_genre_from_movie

app_name = "element"

urlpatterns = [
    path("add-genre/",AddGenre.as_view(),name="add-genre"),
    path("add-cast/",AddCast.as_view(),name="add-cast"),
    path('add-actor/<str:token>/', AddActorToMovie.as_view(), name="add-actor-to-movie"),
    path('delete-cast/<str:token>/', DeleteCast.as_view(), name="delete-cast"),

    path('add-director/<str:token>/', AddDirectorToMovie.as_view(), name="add-director-to-movie"),
    path('remove-actor/<str:film>/<str:actor>/', remove_actor_from_movie, name="remove-actor-from-movie"),
    path('remove-director/<str:film>/<str:director>/', remove_director_from_movie, name="remove-director-from-movie"),
    path('remove-genre/<str:film>/<str:genre>/', remove_genre_from_movie, name="remove-genre-from-movie"),


    path('add-genre/<str:token>/', AddGenreToMovie.as_view(), name="add-genre-to-movie"),


    path("update-cast/<str:token>/",UpdateCast.as_view(),name="update-cast"),
    path("cast-profile/<str:token>/",CastProfile.as_view(),name="profile")
]

apps/movie/urls.py
from django.urls import path
from .views.film import (
    AddMovie, UpdateMovie,
       FilmDetail, DeleteMovie)

from .views.core import (
        HomePage, SearchFilm, FilterGenre
)

from .views.season import AddSeason, SeasonDetail, DeleteSeason

app_name = "movie"

urlpatterns = [
    path("", HomePage, name="home"),

    path("movie-detail/<str:token>/", FilmDetail.as_view(), name="film-detail"),
    path("season-detail/<str:token>/", SeasonDetail.as_view(), name="season-detail"),
    path("add-movie/", AddMovie.as_view(), name="add-movie"),
    path("update-movie/<str:token>/", UpdateMovie.as_view(), name="update-movie"),
    path("delete-movie/<str:token>/", DeleteMovie.as_view(), name="delete-movie"),
    path("add-season/<str:token>/", AddSeason.as_view(), name="add-season"),
    path("delete-season/<str:token>/", DeleteSeason.as_view(), name="delete-season"),

    path("search/<str:name>/", SearchFilm.as_view(), name="search-film"),
    path("filter-genre/<str:genre>/", FilterGenre.as_view(), name="filter-genre"),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("auth/",include("allauth.urls")),
    path("element/",include("apps.element.urls")),
    path("",include("apps.movie.urls")),
    path("api/v1/",include("apps.api.v1.urls")),
    path("api/v2/",include("apps.api.v2.urls")),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'apps.movie.views.core.handler404'
handler500 = 'apps.movie.views.core.handler500'

templates/base/base.html
<!DOCTYPE html>
<html lang="zxx">

<head>
    {%load static%}
    <meta charset="UTF-8">
    <meta name="description" content="Anime Template">
    <meta name="keywords" content="Anime, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{%block title%}{%endblock%}</title>
    <link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
    <script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Mulish:wght@300;400;500;600;700;800;900&display=swap"
    rel="stylesheet">

    <!-- Css Styles -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
</head>

<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

{%include 'base/navbar.html'%}


{%block body%}
{%endblock%}
    

{%include 'base/footer.html'%}

      <div class="search-model">
        <div class="h-100 d-flex align-items-center justify-content-center">
            <div class="search-close-switch"><i class="icon_close"></i></div>
                <input type="text" id="search-input" placeholder="Search here...">
                <button type="submit" class="site-btn" onclick="getInputValue()">Search</button>
                <script src="{% static 'js/search.js' %}"></script>
                <style>
                    #search-input {
                        width: 500px;
                        font-size: 40px;
                        border: none;
                        border-bottom: 2px solid #333;
                        background: 0 0;
                        color: #999;
                    }
                </style>
        </div>
    </div>
    <!-- Js Plugins -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://kit.fontawesome.com/35fb6f5eb9.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/js/jquery.nice-select.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mixitup/3.3.1/mixitup.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/SlickNav/1.0.10/jquery.slicknav.js"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>

</html>

templates/base/footer.html
{%load static%}
    <footer class="footer">
        <div class="page-up">
            <a href="#" id="scrollToTopButton"><span class="arrow_carrot-up"></span></a>
        </div>
        <div class="container">
            <div class="row"> 
                <div class="col-lg-3">
                    <div class="footer__logo" style="color: white;">
                        EZ Anime
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="footer__nav">
                        <ul>
                            <li class="active"><a href="{%url 'movie:home'%}">Homepage</a></li>
                            {%if request.user.is_authenticated%}
                                    <li><a href="{%url 'account_logout'%}">logout</a></li>
                                {%else%}
                                    <li><a href="{%url 'account_login'%}">Login</a></li>
                                {%endif%}
                        </ul>
                    </div>
                </div>
                <div class="col-lg-3" style="color: white;">
                      Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved 

                  </div>
              </div>
          </div>
      </footer>

templates/base/home.html
{%extends 'base/base.html'%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{%block title%}Home page{%endblock%}</title>
</head>
<body>
    {%block body%}
        <section class="product spad">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8">
                        <div class="trending__product">
                            <div class="row">
                                <div class="col-lg-8 col-md-8 col-sm-8">
                                    <div class="section-title">
                                        <h4>Top Rated</h4>
                                    </div>
                                </div>
                                <div class="col-lg-4 col-md-4 col-sm-4">
                                </div>
                            </div>
                            <div class="row">
                                {%for film in films %}
                                    <div class="col-lg-4 col-md-6 col-sm-6">
                                        <div class="product__item">
                                            
                                            <div class="product__item__pic">
                                                <img src="{{film.picture.url}}" alt="na" style="height: 9cm; width: 7cm;">
                                                <div class="comment"><i class="fa fa-star"></i> {{film.imdb}}/10</div>
                                                <div class="view"><i class="fa fa-eye"></i> {{film.views.count}}</div>
                                            </div>
                                            <div class="product__item__text">
                                                <ul>
                                                    {%if not film.seasons.count %}
                                                        <li>Movie</li>
                                                    {%else%}
                                                        <li>Series</li>
                                                    {%endif%}
                                                </ul>
                                                <h5><a href="{%url 'movie:film-detail' film.token%}">{{film.name}}</a></h5>
                                            </div>
                                        </div>
                                    </div>
                                {%endfor%}
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-8">
                        <div class="product__sidebar">
                            <div class="product__sidebar__view">
                                <div class="section-title">
                                    <h5>Top Genres</h5>
                                </div>
                                {%for genre in genres%}
                                    <div class="filter__gallery">
                                        <div class="product__sidebar__view__item">
                                        <div class="view">
                                            <a style="color: white;" href="{%url 'movie:filter-genre' genre.title%}">{{genre.title}}</a>
                                        </div>
                                        <div class="ep">Movies: {{genre.movie_genre.count}}</div>
                                        </div>
                                    </div>
                                {%endfor%}
                </div>
            </div>
        </div>
        <div class="product__sidebar__comment">
            <div class="section-title">
                <h5>Top Viewed Movies</h5>
            </div>
            {%for film in films %}
                <div class="product__sidebar__comment__item">
                    <div class="product__sidebar__comment__item__text">
                        <h5><a href="{%url 'movie:film-detail' film.token%}">{{film.name}}</a></h5>
                        <span>{{film.ratings.count}} person rated</span>
                    </div>
                </div>
            {%endfor%}
        </div>
    </div>
    </div>
    </div>
    </div>
    </section>
    {%endblock%}
</body>
</html>

templates/base/navbar.html
{%load static%}
<header class="header">
        <div class="container">
            <div class="row">
                <div class="col-lg-2">
                    <div class="header__logo">
                        <a style="color: white;" href="{%url 'movie:home'%}">
                            EZ Anime
                        </a>
                    </div>
                </div>
                <div class="col-lg-8">
                    <div class="header__nav">
                        <nav class="header__menu mobile-menu">
                            <ul>
                                <li><a href="{%url 'movie:home'%}">Homepage</a></li>
                                {%if request.user.is_authenticated%}
                                    <li><a href="#">Add <span class="arrow_carrot-down"></span></a>
                                        <ul class="dropdown">
                                            <li><a href="{%url 'movie:add-movie'%}">Movie</a></li>
                                            <li><a href="{%url 'element:add-cast'%}">Element</a></li>

                                        </ul>
                                    </li>
                                {%endif%}
                                {%if request.user.is_authenticated%}
                                    <li><a href="{%url 'account_logout'%}">logout</a></li>
                                {%else%}
                                    <li><a href="#">Auth <span class="arrow_carrot-down"></span></a>
                                        <ul class="dropdown">
                                                <li><a href="{%url 'account_signup'%}">Register</a></li>
                                                <li><a href="{%url 'account_login'%}">Login</a></li>
                                        </ul>
                                    </li>

                                {%endif%}
                                
                            </ul>
                        </nav>
                    </div>
                </div>
                <div class="col-lg-2">
                    <div class="header__right">
                        <a href="#" class="search-switch">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                                <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
                              </svg>
                        </a>
                    </div>
                </div>
            </div>
            <div id="mobile-menu-wrap"></div>
        </div>
    </header>

templates/base/search-result.html
{%extends 'base/base.html'%}
{% load ratings %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   
    <title>{%block title%}Detail page{%endblock%}</title>
</head>
<body>
    {%block body%}
    <section class="anime-details spad">
        <div class="container">
            <div class="anime__details__content">
                <div class="row">
                        <div class="col-lg-8 col-md-8">
                            <div class="anime__details__review">
                                <div class="section-title">
                                    <h5>Result:</h5>
                                </div>
                                {%if not object_list%}
                                <div class="anime__review__item">
                                    <div class="anime__review__item__text">
                                        <h6>No result found</h6>
                                    </div>
                                </div>
                                {%else%}
                                {%for film in object_list%}
                                <h3>{{film.count}}1</h3>
                                    {%if film.count == 0%}
                                        <h3>No result found</h3>
                                    {%else%}
                                        <div class="anime__review__item">
                                            <div class="anime__review__item__pic">
                                                <img src="{{film.picture.url}}" alt="">
                                            </div>
                                            <div class="anime__review__item__text">
                                                <a href="{%url 'movie:film-detail' film.token%}"><h6>{{film.name}}</h6></a>
                                                <a href="{%url 'movie:film-detail' film.token%}"><p>{{film.intro | truncatewords:15}}</p></a>
                                            </div>
                                        </div>
                                    </div>
                                    {%endif%}
                                {%endfor%}
                                {%endif%}
                                
                        </div>
                    </div>
                </div>
            </div>
        </section>
    {%endblock%}
</body>
</html>