apps/element/urls.py
from django.urls import path
from .views.cast import (AddCast, UpdateCast, CastProfile,
                         AddActorToMovie, AddDirectorToMovie,
                         remove_actor_from_movie, remove_director_from_movie,
                            DeleteCast)

from .views.genre import  AddGenre, AddGenreToMovie, remove_genre_from_movie

app_name = "element"

urlpatterns = [
    path("add-genre/",AddGenre.as_view(),name="add-genre"),
    path("add-cast/",AddCast.as_view(),name="add-cast"),
    path('add-actor/<str:token>/', AddActorToMovie.as_view(), name="add-actor-to-movie"),
    path('delete-cast/<str:token>/', DeleteCast.as_view(), name="delete-cast"),

    path('add-director/<str:token>/', AddDirectorToMovie.as_view(), name="add-director-to-movie"),
    path('remove-actor/<str:film>/<str:actor>/', remove_actor_from_movie, name="remove-actor-from-movie"),
    path('remove-director/<str:film>/<str:director>/', remove_director_from_movie, name="remove-director-from-movie"),
    path('remove-genre/<str:film>/<str:genre>/', remove_genre_from_movie, name="remove-genre-from-movie"),


    path('add-genre/<str:token>/', AddGenreToMovie.as_view(), name="add-genre-to-movie"),


    path("update-cast/<str:token>/",UpdateCast.as_view(),name="update-cast"),
    path("cast-profile/<str:token>/",CastProfile.as_view(),name="profile")
]

apps/movie/urls.py
from django.urls import path
from .views.film import (
    AddMovie, UpdateMovie,
       FilmDetail, DeleteMovie)

from .views.core import (
        HomePage, SearchFilm, FilterGenre
)

from .views.season import AddSeason, SeasonDetail, DeleteSeason

app_name = "movie"

urlpatterns = [
    path("", HomePage, name="home"),

    path("movie-detail/<str:token>/", FilmDetail.as_view(), name="film-detail"),
    path("season-detail/<str:token>/", SeasonDetail.as_view(), name="season-detail"),
    path("add-movie/", AddMovie.as_view(), name="add-movie"),
    path("update-movie/<str:token>/", UpdateMovie.as_view(), name="update-movie"),
    path("delete-movie/<str:token>/", DeleteMovie.as_view(), name="delete-movie"),
    path("add-season/<str:token>/", AddSeason.as_view(), name="add-season"),
    path("delete-season/<str:token>/", DeleteSeason.as_view(), name="delete-season"),

    path("search/<str:name>/", SearchFilm.as_view(), name="search-film"),
    path("filter-genre/<str:genre>/", FilterGenre.as_view(), name="filter-genre"),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("auth/",include("allauth.urls")),
    path("element/",include("apps.element.urls")),
    path("",include("apps.movie.urls")),
    path("api/v1/",include("apps.api.v1.urls")),
    path("api/v2/",include("apps.api.v2.urls")),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'apps.movie.views.core.handler404'
handler500 = 'apps.movie.views.core.handler500'

apps/element/models.py
from django.db import models


class Genre(models.Model):
    title = models.CharField(max_length=120)

    def __str__(self) :
        return self.title


class Cast(models.Model):

    class role(models.TextChoices):
        actor = "a"
        director = "d"

    avatar = models.ImageField(upload_to="actors/")
    full_name = models.CharField(max_length=50, null=True)

    biography = models.TextField()
    birthday  = models.DateField()

    role = models.CharField(max_length=1, choices=role.choices,default=role.actor)
    token = models.CharField(max_length=10,blank=True)

    def __str__(self):
        return self.full_name


class Tag(models.Model):
    title = models.CharField(max_length=120)
        
    def __str__(self):
        return self.title

apps/element/forms.py
from django import  forms
from django.forms import ModelForm
from .models import Genre,Cast

class GenreForm(ModelForm):
    class Meta:
        model = Genre
        fields = ('title',)

class CastForm(ModelForm):
    class Meta:
        model = Cast
        fields = ("avatar","full_name","biography","birthday","role")


class MovieActorForm(ModelForm):
    actor = forms.ModelChoiceField(queryset= Cast.objects.filter(role="a"))
    class Meta:
        model =  Cast
        fields = ["actor"]


class MovieDirectorForm(ModelForm):
    director = forms.ModelChoiceField(queryset= Cast.objects.filter(role="d"))

    class Meta:
        model =  Cast
        fields = ["director"]


class MovieGenreForm(ModelForm):
    genre = forms.ModelChoiceField(queryset= Genre.objects.all())

    class Meta:
        model = Genre
        fields = ["genre"]

apps/element/views/cast.py
from django.shortcuts import redirect, get_object_or_404
from django.views.generic import FormView, DetailView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin

import uuid

from element.models import Cast
from movie.models import Film

from element.forms import CastForm, MovieActorForm, MovieDirectorForm

class CastProfile(DetailView):
    '''Cast Profile page'''
    template_name = "element/cast/cast-profile.html"

    def get_object(self, **kwarg):
        return get_object_or_404(Cast, token=self.kwargs['token'])


class AddCast(LoginRequiredMixin, FormView):
    '''Add actor or Director to database'''

    template_name = "element/cast/add-cast.html"
    form_class = CastForm

    def form_valid(self, form):
        form = self.form_class(self.request.POST, self.request.FILES)
        form = form.save(commit=False)
        form.token = uuid.uuid4().hex.upper()[0:10]
        form.save()
        return redirect("movie:home")

    def form_invalid(self, form):
        return redirect("element:add-cast")


class UpdateCast(LoginRequiredMixin, UpdateView):
    '''Update a cast information'''

    template_name = "element/cast/update-cast.html"
    fields = ["full_name", 'biography', 'birthday', 'role', 'avatar']
    success_url = "/"

    def get_object(self):
        return get_object_or_404(Cast, token=self.kwargs['token'])


class DeleteCast(LoginRequiredMixin, DeleteView):
    '''Delete a cast'''
    template_name = "element/cast/delete-cast.html"
    success_url = "/"

    def get_object(self):
        return get_object_or_404(Cast, token=self.kwargs["token"])



class AddActorToMovie(LoginRequiredMixin, FormView):
    '''Add Actor for a movie'''

    form_class = MovieActorForm
    template_name = "element/cast/add-actor-to-film.html"

    def form_valid(self, form):

        film = get_object_or_404(Film,
                                 token=self.kwargs["token"])

        actor = get_object_or_404(Cast, full_name= form.cleaned_data["actor"],
                                  role="a")

        if not actor in film.actors.all():
            film.actors.add(actor)
            return redirect("movie:film-detail", token=film.token)

        return redirect("movie:film-detail", token=film.token)


    def form_invalid(self, form):
        return redirect("movie:home")


def remove_actor_from_movie(request, film, actor):
    # remove an actor from actors list
    if request.method == "GET" and request.user.is_authenticated:

        film = get_object_or_404(Film, token=film)
        actor = get_object_or_404(Cast, token=actor)

        if actor in film.actors.all():
            film.actors.remove(actor)
            return redirect("movie:film-detail", token=film.token)
        return redirect("movie:film-detail", token=film.token)

    return redirect("movie:film-detail", token=film.token)

def remove_director_from_movie(request, film, director):
    # remove an director from director list
    if request.method == "GET" and request.user.is_authenticated:

        film = get_object_or_404(Film, token=film)
        director = get_object_or_404(Cast, token=director)

        if director in film.director.all():
            film.director.remove(director)
            return redirect("movie:film-detail", token=film.token)
        return redirect("movie:film-detail", token=film.token)

    return redirect("movie:film-detail", token=film.token)

class AddDirectorToMovie(LoginRequiredMixin, FormView):
    '''Add Director for a movie'''

    form_class = MovieDirectorForm
    template_name = "element/cast/add-director-to-film.html"

    def form_valid(self, form):

        film = get_object_or_404(Film,
                                 token=self.kwargs["token"])

        director = get_object_or_404(Cast, full_name= form.cleaned_data["director"],
                                  role="d")

        if not director in film.director.all():
            film.director.add(director)
            return redirect("movie:film-detail", token=film.token)

        return redirect("movie:film-detail", token=film.token)


    def form_invalid(self, form):
        return redirect("movie:home")

apps/element/views/genre.py
from django.shortcuts import redirect, get_object_or_404
from django.views.generic import FormView
from django.contrib.auth.mixins import LoginRequiredMixin

from element.forms import GenreForm, MovieGenreForm
from movie.models import Film
from element.models import Genre


class AddGenre(LoginRequiredMixin, FormView):
    '''Add a genre to db'''

    template_name = "element/genre/add-genre.html"
    form_class = GenreForm

    def form_valid(self, form):
        title = form.cleaned_data.get("title")

        if Genre.objects.filter(title=title).exists():
            return redirect("movie:home")

        form.save()
        return redirect("movie:home")

    def form_invalid(self, form):
        return redirect("element:add-genre")



class AddGenreToMovie(LoginRequiredMixin, FormView):
    '''Add Genre for a movie'''

    form_class = MovieGenreForm
    template_name = "element/genre/add-genre-to-film.html"

    def form_valid(self, form):

        film = get_object_or_404(Film,
                                 token=self.kwargs["token"])

        genre = get_object_or_404(Genre, title=form.cleaned_data["genre"])

        if not genre in film.genre.all():
            film.genre.add(genre)
            return redirect("movie:film-detail", token=film.token)

        return redirect("movie:film-detail", token=film.token)


    def form_invalid(self, form):
        return redirect("movie:home")


def remove_genre_from_movie(request, film, genre):
    # remove genre from movie
    if request.method == "GET" and request.user.is_authenticated:

        film = get_object_or_404(Film, token=film)
        genre = get_object_or_404(Genre, title=genre)

        if genre in film.genre.all():
            film.genre.remove(genre)
            return redirect("movie:film-detail", token=film.token)

        return redirect("movie:film-detail", token=film.token)

    return redirect("movie:film-detail", token=film.token)

apps/element/templates/element/cast/add-actor-to-film.html
{%extends 'element/base-element.html'%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{%block title%}Add Actor{%endblock%}</title>
   {%block page_title%}Add Actor{%endblock%}
</head>
<body>


        {%block main%}
                            <div class="input__item">
                                    <select name="actor" required="" id="id_acctor" style="width:300px;">
                                        <option>
                                            {% for actor in form.actor %}
                                                {{ actor }}
                                            {% endfor %}
                                        </option>
                                    </select>
                            </div><br>

                    <br><button type="submit" class="site-btn">Submit</button>
        {%endblock%}


        {% block side %}
            <h3 style="color:white;">Actor Not Listed?</h3> <br>
            <a href="{% url 'element:add-cast' %}" class="site-btn">Add Actor</a>
        {% endblock %}
</body>
</html>

apps/element/templates/element/cast/add-cast.html
{%extends 'element/base-element.html'%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{%block title%}Add cast{%endblock%}</title>
   {%block page_title%}Add Cast{%endblock%}
</head>
<body>


        {%block main%}
                            <div class="input__item">
                                <input name="full_name" type="text" placeholder="Full Name" maxlength="20" style="width: 10cm; height: 1.5cm;">
                            </div><br>
                            {{form.role}}<br><br>
                            {{form.avatar}}<br><br>
        {%endblock%}

        {% block side %}
            <div class="input__item">
                <input name="biography" type="text" placeholder="Short biography" style="width: 10cm; height: 4cm;">
            </div>
            <div class="input__item">
                <input name="birthday" type="date" placeholder="birthday date" style="width: 10cm; height: 1.5cm;">
            </div>
            <br><button type="submit" class="site-btn">Submit</button>
        {% endblock %}
</body>
</html>

apps/element/templates/element/cast/add-director-to-film.html
{%extends 'element/base-element.html'%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{%block title%}Add Director{%endblock%}</title>
   {%block page_title%}Add Director{%endblock%}
</head>
<body>


        {%block main%}
                            <div class="input__item">
                                    <select name="director" required="" id="id_director" style="width:300px;">
                                        <option>
                                            {% for director in form.director %}
                                                {{ director }}
                                            {% endfor %}
                                        </option>
                                    </select>
                            </div><br>

                    <br><button type="submit" class="site-btn">Submit</button>
        {%endblock%}


        {% block side %}
            <h3 style="color:white;">Director Not Listed?</h3> <br>
            <a href="{% url 'element:add-cast' %}" class="site-btn">Add Director</a>
        {% endblock %}
</body>
</html>

apps/element/templates/element/cast/cast-profile.html
{%extends 'element/base-element.html'%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{%block title%}Profile page{%endblock%}</title>
   {%block page_title%}profile page{%endblock%}
</head>
<body>
    {%block main%}

    <img src="{{object.avatar.url}}" alt="avatar">
    <br><br>
    <h3>{{object.full_name}}</h3>
    <p style="color: white;">Birth date: {{object.birthday}}</p>

    {%endblock%}

    {% block side %}
        <h3 style="color:white;">Biography</h3>
        <p style="color: white;">{{object.biography}}</p>

        <h3 style="color:white;">Works</h3>

        {%for work in object.movie_actor.all %}
            <a href="{%url 'movie:film-detail' work.token%}">{{work}} | </a>
        {% empty %}
            <p style="color:white;">EMPTY</p>
        {%endfor%}
        <br>
        {%if request.user.is_authenticated%}
            <br>
            <a href="{%url 'element:update-cast' object.token%}" class="site-btn">Update</a>
            <br> <br>
            <a href="{%url 'element:delete-cast' object.token%}" class="site-btn">Delete</a>
        {%endif%}
    {% endblock %}
</body>
</html>

apps/element/templates/element/cast/delete-cast.html
{%extends 'element/base-element.html'%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{%block title%}Update cast{%endblock%}</title>
   {%block page_title%}Update Cast{%endblock%}
</head>

<body>

    {%block main%}
    <h3 style="color:white;">Are you sure about deleting <a href="{% url 'element:profile' object.token %}">{{ object.full_name }}</a>?</h3>
        <form method="post">
            <button class="site-btn">Delete</button>
        </form>
    {%endblock%}


</body>
</html>

apps/element/templates/element/cast/update-cast.html
{%extends 'element/base-element.html'%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{%block title%}Update cast{%endblock%}</title>
   {%block page_title%}Update Cast{%endblock%}
</head>

<body>

    {%block main%}

        <div class="input__item">
            <input name="full_name" type="text" placeholder="Full Name" value="{{form.full_name.value}}" maxlength="20">
        </div><br>
        {{form.role}}<br><br>
        {{form.avatar}}<br><br>
    <style>
        input{
            width: 10cm; height: 1.5cm;
        }
    </style>
    {%endblock%}

    {% block side %}
                        <div class="input__item">
                            <input name="biography" type="text" placeholder="Short biography" value="{{form.biography.value}}">
                        </div>

                        <br>

                        <div class="input__item">
                            <input name="birthday" type="date" placeholder="birthday date" value="{{form.birthday.value}}" >
                        </div>

                        <br><button type="submit" class="site-btn">Submit</button>
    {%endblock%}

</body>
</html>